# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Master/2025/Mamba/Cmamba_reconstruct/user/ip/bias_ROM/bias_ROM.xci
# IP: The module: 'bias_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Master/2025/Mamba/project_reconstruct.gen/sources_1/ip/bias_ROM/bias_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bias_ROM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/Master/2025/Mamba/Cmamba_reconstruct/user/ip/bias_ROM/bias_ROM.xci
# IP: The module: 'bias_ROM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Master/2025/Mamba/project_reconstruct.gen/sources_1/ip/bias_ROM/bias_ROM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bias_ROM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
