# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.srcs/sources_1/ip/u_xt_rom/u_xt_rom.xci
# IP: The module: 'u_xt_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.gen/sources_1/ip/u_xt_rom/u_xt_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_xt_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.srcs/sources_1/ip/u_xt_rom/u_xt_rom.xci
# IP: The module: 'u_xt_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.gen/sources_1/ip/u_xt_rom/u_xt_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'u_xt_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
