%% Remove only err_vis folders generated by batch script
dataRoot = 'E:\course\master\mamba\Cmamba_reconstruct\test_out';

% get all items named err_vis
d = dir(fullfile(dataRoot,'**','err_vis'));

fprintf("Found %d err_vis matches.\n", numel(d));

for i = 1:numel(d)
    folder = fullfile(d(i).folder, d(i).name);

    % only delete if it's truly a folder
    if isfolder(folder)
        fprintf("Deleting folder: %s\n", folder);
        rmdir(folder, 's');
    else
        fprintf("Skip (not folder): %s\n", folder);
    end
end

disp("🧹 Clean complete.");
