# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/.Xil/Vivado-23464-G14-DAWN/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu9eg-ffvb1156-2-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      E:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv {
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/array4x4.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/axis_vec_join2.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/bias_add_regslice_ip.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ew_update_vec4.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ewa_vec4.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ewm_gate_sbuf_vec4.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ewm_vec4.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pe_unit_pipe.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pipeline_4array_top.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pipeline_4array_with_reduction.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pulse_to_stream_adapter.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/reduction_accumulator.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/sigmoid4_vec.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/slim_mac_mem_controller_combined_dp.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/slim_multi_bank_wbuf_dp.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/vec_fifo_axis_ip.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/xt_input_buf.sv
      E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/top_mac_plus_bias_fifo_sigmoid_ew_gate.sv
    }
      rt::read_verilog {
      E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/.Xil/Vivado-23464-G14-DAWN/realtime/s_buffer_stub.v
      E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/.Xil/Vivado-23464-G14-DAWN/realtime/bias2sigmoid_fifo_stub.v
      E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/.Xil/Vivado-23464-G14-DAWN/realtime/bias_ROM_stub.v
      E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/.Xil/Vivado-23464-G14-DAWN/realtime/slim_WBUF_bank_dp_stub.v
      E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/.Xil/Vivado-23464-G14-DAWN/realtime/u_xt_rom_stub.v
    }
      rt::read_vhdl -lib xpm E:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top_mac_plus_bias_fifo_sigmoid_ew_gate
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/.Xil/Vivado-23464-G14-DAWN/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
