# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Mamba/CMamba_refactor/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/norm_gamma_rom_ip_1/norm_gamma_rom_ip.xci
# IP: The module: 'norm_gamma_rom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mamba/CMamba_refactor/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/norm_gamma_rom_ip_1/norm_gamma_rom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'norm_gamma_rom_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Mamba/CMamba_refactor/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/norm_gamma_rom_ip_1/norm_gamma_rom_ip.xci
# IP: The module: 'norm_gamma_rom_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Mamba/CMamba_refactor/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/norm_gamma_rom_ip_1/norm_gamma_rom_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'norm_gamma_rom_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
