# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/s_buffer/s_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==s_buffer || ORIG_REF_NAME==s_buffer} -quiet] -quiet
