# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.runs/synth_1/top_mac_plus_bias_fifo_sigmoid_ew_gate.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param checkpoint.writeSynthRtdsInDcp 1
set_param power.enableLutRouteBelPower 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.cache/wt [current_project]
set_property parent.project_path E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.4 [current_project]
set_property ip_output_repo e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib -sv {
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/array4x4.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/axis_vec_join2.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/bias_add_regslice_ip.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ew_update_vec4.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ewa_vec4.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ewm_gate_sbuf_vec4.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/ewm_vec4.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pe_unit_pipe.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pipeline_4array_top.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pipeline_4array_with_reduction.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/pulse_to_stream_adapter.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/reduction_accumulator.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/sigmoid4_vec.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/slim_mac_mem_controller_combined_dp.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/slim_multi_bank_wbuf_dp.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/vec_fifo_axis_ip.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/xt_input_buf.sv
  E:/Master/2025/Mamba/Cmamba_reconstruct/user/src/top_mac_plus_bias_fifo_sigmoid_ew_gate.sv
}
read_ip -quiet e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.srcs/sources_1/ip/s_buffer/s_buffer.xci
set_property used_in_implementation false [get_files -all e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.gen/sources_1/ip/s_buffer/s_buffer_ooc.xdc]

read_ip -quiet E:/Master/2025/Mamba/Cmamba_reconstruct/user/ip/bias2sigmoid_fifo/bias2sigmoid_fifo.xci
set_property used_in_implementation false [get_files -all e:/Master/2025/Mamba/project_reconstruct.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/Master/2025/Mamba/project_reconstruct.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo_ooc.xdc]

read_ip -quiet E:/Master/2025/Mamba/Cmamba_reconstruct/user/ip/bias_ROM/bias_ROM.xci
set_property used_in_implementation false [get_files -all e:/Master/2025/Mamba/project_reconstruct.gen/sources_1/ip/bias_ROM/bias_ROM_ooc.xdc]

read_ip -quiet E:/Master/2025/Mamba/Cmamba_reconstruct/user/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp.xci
set_property used_in_implementation false [get_files -all e:/Master/2025/Mamba/project_reconstruct.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp_ooc.xdc]

read_ip -quiet e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.srcs/sources_1/ip/u_xt_rom/u_xt_rom.xci
set_property used_in_implementation false [get_files -all e:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.gen/sources_1/ip/u_xt_rom/u_xt_rom_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/Master/2025/Mamba/Cmamba_reconstruct/prj/xilinx/project_reconstruct.srcs/utils_1/imports/synth_1/top_mac_plus_bias_fifo_sigmoid_ew_gate.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top top_mac_plus_bias_fifo_sigmoid_ew_gate -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_mac_plus_bias_fifo_sigmoid_ew_gate.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file top_mac_plus_bias_fifo_sigmoid_ew_gate_utilization_synth.rpt -pb top_mac_plus_bias_fifo_sigmoid_ew_gate_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
