# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xczu9eg-ffvb1156-2-e
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include E:/course/smamba/HW_reconstruct/hw_debug/vivado_runs/reuse_mamba_block_top_hw_debug {
      E:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      E:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -sv -include E:/course/smamba/HW_reconstruct/hw_debug/vivado_runs/reuse_mamba_block_top_hw_debug {
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/axis_vec_join2.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/bias_add_regslice_ip.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ew_update_vec4.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ewa_vec4.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ewm_gate_sbuf_vec4.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ewm_vec4.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/pe_unit_pipe.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/pulse_to_stream_adapter.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/requant_round_sat_engine.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_array4x4.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ht_multi_copy_ip.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ht_sram.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ht_sram_sp.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_in_proj_scheduler.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_inproj_weight_sram.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ip_blackboxes.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mac_fabric_manager.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_axi_lite_regs.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_block_top.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_block_wrapper.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_out_proj_scheduler.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_outproj_multi_bank_wbuf_dp.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_outproj_weight_sram.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_packed_scale_mem.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_pipeline_4array_top.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_pipeline_4array_with_reduction.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_pt_capture.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_reduction_accumulator.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_shared_mac_fabric.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_silu_vec4.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ssm_core.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ssm_dt_scheduler.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_vec_out_sram.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_vec_out_sram_ip.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_z_stream_reader.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/sigmoid4_vec.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/slim_multi_bank_wbuf_dp.sv
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/vec_fifo_axis_ip.sv
    }
      rt::read_verilog -include E:/course/smamba/HW_reconstruct/hw_debug/vivado_runs/reuse_mamba_block_top_hw_debug {
      E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/s_buffer_stub.v
      E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/bias2sigmoid_fifo_stub.v
      E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/bias_ROM_stub.v
      E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/inproj_vec_out_sram_ip_stub.v
      E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/outproj_WBUF_bank_dp_stub.v
      E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/slim_WBUF_bank_dp_stub.v
      E:/course/smamba/.Xil/Vivado-112064-13600kf/realtime/inproj_ht_sram_ip_stub.v
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_h_stream_loader.v
      E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_board_shell.v
    }
      rt::read_vhdl -lib xpm E:/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top reuse_mamba_board_shell
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter linterFlow true
    rt::set_parameter synthReportEmptyAndUndriven false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/course/smamba/.Xil/Vivado-112064-13600kf/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
