`timescale 1ns/1ps
//---------------------------------------------------------------
// Module: reuse_mamba_block_wrapper
// Function:
//   Thin integration wrapper for reuse_mamba_block_top.
//   - Synchronizes the external active-low reset into sys_clk
//   - Flattens 4-lane vector ports into packed buses
//   - Keeps the compute core interface explicit for board integration
//---------------------------------------------------------------
module reuse_mamba_block_wrapper #(
    parameter int TILE_SIZE  = 4,
    parameter int DATA_WIDTH = 16,
    parameter int ACC_WIDTH  = 32,
    parameter int FRAC_BITS  = 8,
    parameter int N_BANK     = 6,
    parameter int WDEPTH     = 1024,
    parameter int WADDR_W    = $clog2(WDEPTH),
    parameter int DATA_W     = 256,
    parameter int XT_ADDR_W  = 6,
    parameter int D          = 256,
    parameter int PIPE_LAT   = 4,
    parameter int ADDR_BITS  = 11,
    parameter string LUT_FILE = "sigmoid_lut_q016_2048.hex",
    parameter int S_ADDR_W   = 6,
    parameter int G_FRAC_BITS = 8,
    parameter string INPROJ_BANK0_INIT_FILE = "",
    parameter string INPROJ_BANK1_INIT_FILE = "",
    parameter string INPROJ_BANK2_INIT_FILE = "",
    parameter string INPROJ_BANK3_INIT_FILE = "",
    parameter string INPROJ_BANK4_INIT_FILE = "",
    parameter string INPROJ_BANK5_INIT_FILE = "",
    parameter string INPROJ_SCALE_INIT_FILE = "",
    parameter string DT_BANK0_INIT_FILE = "",
    parameter string DT_BANK1_INIT_FILE = "",
    parameter string DT_BANK2_INIT_FILE = "",
    parameter string DT_BANK3_INIT_FILE = "",
    parameter string DT_SCALE_INIT_FILE = "",
    parameter string OUTPROJ_BANK0_INIT_FILE = "",
    parameter string OUTPROJ_BANK1_INIT_FILE = "",
    parameter string OUTPROJ_BANK2_INIT_FILE = "",
    parameter string OUTPROJ_BANK3_INIT_FILE = "",
    parameter string OUTPROJ_BANK4_INIT_FILE = "",
    parameter string OUTPROJ_BANK5_INIT_FILE = "",
    parameter string OUTPROJ_SCALE_INIT_FILE = "",
    parameter bit ENABLE_RMSNORM = 0,
    parameter string NORM_GAMMA_INIT_FILE = "",
    parameter bit USE_SCALED_STATE_SCAN = 0,
    parameter string STATE_U_TO_STATE_SCALE_INIT_FILE = "",
    parameter string STATE_TO_Q88_SCALE_INIT_FILE = ""
)(
    input  logic sys_clk,
    input  logic ext_reset_n,
    output logic core_rst_n_o,

    input  logic block_auto_mode,
    input  logic block_start,
    output logic block_busy,
    output logic block_done,

    input  logic                         s_axis_tvalid,
    output logic                         s_axis_tready,
    output logic                         y_axis_tvalid,
    input  logic                         y_axis_tready,
    output logic signed [TILE_SIZE*DATA_WIDTH-1:0] y_axis_tdata,

    input  logic                         inproj_enable,
    input  logic                         inproj_start,
    output logic                         inproj_busy,
    output logic                         inproj_done,
    input  logic                         h_wr_en,
    input  logic [4:0]                   h_wr_addr,
    input  logic signed [TILE_SIZE*DATA_WIDTH-1:0] h_wr_data,
    input  logic                         u_rd_en,
    input  logic [5:0]                   u_rd_addr,
    output logic signed [TILE_SIZE*DATA_WIDTH-1:0] u_rd_data,
    input  logic                         z_rd_en,
    input  logic [5:0]                   z_rd_addr,
    output logic signed [TILE_SIZE*DATA_WIDTH-1:0] z_rd_data,

    input  logic                         outproj_enable,
    output logic                         outproj_busy
);
    // Wrapper entry to the board-side adapter.
    reuse_mamba_core_adapter #(
        .TILE_SIZE   (TILE_SIZE),
        .DATA_WIDTH  (DATA_WIDTH),
        .ACC_WIDTH   (ACC_WIDTH),
        .FRAC_BITS   (FRAC_BITS),
        .N_BANK      (N_BANK),
        .WDEPTH      (WDEPTH),
        .WADDR_W     (WADDR_W),
        .DATA_W      (DATA_W),
        .XT_ADDR_W   (XT_ADDR_W),
        .D           (D),
        .PIPE_LAT    (PIPE_LAT),
        .ADDR_BITS   (ADDR_BITS),
        .LUT_FILE    (LUT_FILE),
        .S_ADDR_W    (S_ADDR_W),
        .G_FRAC_BITS (G_FRAC_BITS),
        .INPROJ_BANK0_INIT_FILE (INPROJ_BANK0_INIT_FILE),
        .INPROJ_BANK1_INIT_FILE (INPROJ_BANK1_INIT_FILE),
        .INPROJ_BANK2_INIT_FILE (INPROJ_BANK2_INIT_FILE),
        .INPROJ_BANK3_INIT_FILE (INPROJ_BANK3_INIT_FILE),
        .INPROJ_BANK4_INIT_FILE (INPROJ_BANK4_INIT_FILE),
        .INPROJ_BANK5_INIT_FILE (INPROJ_BANK5_INIT_FILE),
        .INPROJ_SCALE_INIT_FILE (INPROJ_SCALE_INIT_FILE),
        .DT_BANK0_INIT_FILE     (DT_BANK0_INIT_FILE),
        .DT_BANK1_INIT_FILE     (DT_BANK1_INIT_FILE),
        .DT_BANK2_INIT_FILE     (DT_BANK2_INIT_FILE),
        .DT_BANK3_INIT_FILE     (DT_BANK3_INIT_FILE),
        .DT_SCALE_INIT_FILE     (DT_SCALE_INIT_FILE),
        .OUTPROJ_BANK0_INIT_FILE(OUTPROJ_BANK0_INIT_FILE),
        .OUTPROJ_BANK1_INIT_FILE(OUTPROJ_BANK1_INIT_FILE),
        .OUTPROJ_BANK2_INIT_FILE(OUTPROJ_BANK2_INIT_FILE),
        .OUTPROJ_BANK3_INIT_FILE(OUTPROJ_BANK3_INIT_FILE),
        .OUTPROJ_BANK4_INIT_FILE(OUTPROJ_BANK4_INIT_FILE),
        .OUTPROJ_BANK5_INIT_FILE(OUTPROJ_BANK5_INIT_FILE),
        .OUTPROJ_SCALE_INIT_FILE(OUTPROJ_SCALE_INIT_FILE),
        .ENABLE_RMSNORM(ENABLE_RMSNORM),
        .NORM_GAMMA_INIT_FILE(NORM_GAMMA_INIT_FILE),
        .USE_SCALED_STATE_SCAN(USE_SCALED_STATE_SCAN),
        .STATE_U_TO_STATE_SCALE_INIT_FILE(STATE_U_TO_STATE_SCALE_INIT_FILE),
        .STATE_TO_Q88_SCALE_INIT_FILE(STATE_TO_Q88_SCALE_INIT_FILE)
    ) u_core (
        .sys_clk        (sys_clk),
        .ext_reset_n    (ext_reset_n),
        .core_rst_n_o   (core_rst_n_o),
        .block_auto_mode(block_auto_mode),
        .block_start    (block_start),
        .block_busy     (block_busy),
        .block_done     (block_done),
        .s_axis_tvalid  (s_axis_tvalid),
        .s_axis_tready  (s_axis_tready),
        .y_axis_tvalid  (y_axis_tvalid),
        .y_axis_tready  (y_axis_tready),
        .y_axis_tdata   (y_axis_tdata),
        .inproj_enable  (inproj_enable),
        .inproj_start   (inproj_start),
        .inproj_busy    (inproj_busy),
        .inproj_done    (inproj_done),
        .h_wr_en        (h_wr_en),
        .h_wr_addr      (h_wr_addr),
        .h_wr_data      (h_wr_data),
        .u_rd_en        (u_rd_en),
        .u_rd_addr      (u_rd_addr),
        .u_rd_data      (u_rd_data),
        .z_rd_en        (z_rd_en),
        .z_rd_addr      (z_rd_addr),
        .z_rd_data      (z_rd_data),
        .outproj_enable (outproj_enable),
        .outproj_busy   (outproj_busy)
    );
endmodule
