# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/course/smamba/HW_reconstruct/minimal_timing.xdc

# IP: ip/s_buffer/s_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==s_buffer || ORIG_REF_NAME==s_buffer} -quiet] -quiet

# IP: ip/bias2sigmoid_fifo/bias2sigmoid_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias2sigmoid_fifo || ORIG_REF_NAME==bias2sigmoid_fifo} -quiet] -quiet

# IP: ip/bias_ROM/bias_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_ROM || ORIG_REF_NAME==bias_ROM} -quiet] -quiet

# IP: ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inproj_vec_out_sram_ip || ORIG_REF_NAME==inproj_vec_out_sram_ip} -quiet] -quiet
