# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: E:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/minimal_timing.xdc

# IP: ip/s_buffer/s_buffer.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==s_buffer || ORIG_REF_NAME==s_buffer} -quiet] -quiet

# IP: ip/bias2sigmoid_fifo/bias2sigmoid_fifo.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias2sigmoid_fifo || ORIG_REF_NAME==bias2sigmoid_fifo} -quiet] -quiet

# IP: ip/bias_ROM/bias_ROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_ROM || ORIG_REF_NAME==bias_ROM} -quiet] -quiet

# IP: ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inproj_vec_out_sram_ip || ORIG_REF_NAME==inproj_vec_out_sram_ip} -quiet] -quiet

# IP: ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==outproj_WBUF_bank_dp || ORIG_REF_NAME==outproj_WBUF_bank_dp} -quiet] -quiet

# IP: ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slim_WBUF_bank_dp || ORIG_REF_NAME==slim_WBUF_bank_dp} -quiet] -quiet

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_zynq_ultra_ps_e_0_0/design_1_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==design_1_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_0/design_1_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_0 || ORIG_REF_NAME==design_1_smartconnect_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_smartconnect_0_1/design_1_smartconnect_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_smartconnect_0_1 || ORIG_REF_NAME==design_1_smartconnect_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_0/design_1_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_0 || ORIG_REF_NAME==design_1_axi_dma_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi_dma_0_1/design_1_axi_dma_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi_dma_0_1 || ORIG_REF_NAME==design_1_axi_dma_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_reuse_mamba_board_sh_0_1/design_1_reuse_mamba_board_sh_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_reuse_mamba_board_sh_0_1 || ORIG_REF_NAME==design_1_reuse_mamba_board_sh_0_1} -quiet] -quiet

# IP: ip/inproj_ht_sram_ip/inproj_ht_sram_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inproj_ht_sram_ip || ORIG_REF_NAME==inproj_ht_sram_ip} -quiet] -quiet

# IP: ip/s_buffer/s_buffer.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==s_buffer || ORIG_REF_NAME==s_buffer} -quiet] -quiet

# IP: ip/bias2sigmoid_fifo/bias2sigmoid_fifo.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias2sigmoid_fifo || ORIG_REF_NAME==bias2sigmoid_fifo} -quiet] -quiet

# IP: ip/bias_ROM/bias_ROM.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==bias_ROM || ORIG_REF_NAME==bias_ROM} -quiet] -quiet

# IP: ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==inproj_vec_out_sram_ip || ORIG_REF_NAME==inproj_vec_out_sram_ip} -quiet] -quiet

# IP: ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==outproj_WBUF_bank_dp || ORIG_REF_NAME==outproj_WBUF_bank_dp} -quiet] -quiet

# IP: ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==slim_WBUF_bank_dp || ORIG_REF_NAME==slim_WBUF_bank_dp} -quiet] -quiet

# XDC: e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/bd/design_1/design_1_ooc.xdc
