# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.runs/synth_1/reuse_mamba_board_shell.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param bd.open.in_stealth_mode 2
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu9eg-ffvb1156-2-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.cache/wt [current_project]
set_property parent.project_path E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:zcu102:part0:3.4 [current_project]
set_property ip_output_repo e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
add_files E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/inproj_vec_out_sram_ip/INIT_COE.coe
read_mem E:/course/smamba/HW_reconstruct/hw_debug/vivado_runs/reuse_mamba_block_top_hw_debug/sigmoid_lut_q016_2048.hex
read_verilog -library xil_defaultlib -sv {
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/axis_vec_join2.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/bias_add_regslice_ip.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ew_update_vec4.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ewa_vec4.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ewm_gate_sbuf_vec4.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/ewm_vec4.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/pe_unit_pipe.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/pulse_to_stream_adapter.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/requant_round_sat_engine.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_array4x4.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ht_multi_copy_ip.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ht_sram.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ht_sram_sp.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_in_proj_scheduler.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_inproj_weight_sram.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mac_fabric_manager.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_axi_lite_regs.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_block_top.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_block_wrapper.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_out_proj_scheduler.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_outproj_weight_sram.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_packed_scale_mem.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_pipeline_4array_top.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_pipeline_4array_with_reduction.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_pt_capture.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_reduction_accumulator.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_shared_mac_fabric.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_silu_vec4.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ssm_core.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_ssm_dt_scheduler.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_vec_out_sram.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_vec_out_sram_ip.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_weight_bank_rom.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_z_stream_reader.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/sigmoid4_vec.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/slim_multi_bank_wbuf_dp.sv
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/vec_fifo_axis_ip.sv
}
read_verilog -library xil_defaultlib {
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_h_stream_loader.v
  E:/course/smamba/HW_reconstruct/rtl_reuse_shared/reuse_mamba_board_shell.v
}
read_ip -quiet E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/s_buffer/s_buffer.xci
set_property used_in_implementation false [get_files -all e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/s_buffer/s_buffer_ooc.xdc]

read_ip -quiet E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo.xci
set_property used_in_implementation false [get_files -all e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo.xdc]
set_property used_in_implementation false [get_files -all e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo_ooc.xdc]

read_ip -quiet E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/inproj_ht_sram_ip/inproj_ht_sram_ip.xci
set_property used_in_implementation false [get_files -all e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip/inproj_ht_sram_ip_ooc.xdc]

read_ip -quiet E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/bias_ROM/bias_ROM.xci
set_property used_in_implementation false [get_files -all e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias_ROM/bias_ROM_ooc.xdc]

read_ip -quiet E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip.xci
set_property used_in_implementation false [get_files -all e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/course/smamba/HW_reconstruct/minimal_timing.xdc
set_property used_in_implementation false [get_files E:/course/smamba/HW_reconstruct/minimal_timing.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/utils_1/imports/synth_1/reuse_mamba_block_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top reuse_mamba_board_shell -part xczu9eg-ffvb1156-2-e
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef reuse_mamba_board_shell.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file reuse_mamba_board_shell_utilization_synth.rpt -pb reuse_mamba_board_shell_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
