`timescale 1ns/1ps
//---------------------------------------------------------------
// Module: slm_exact_outproj_stage
// Function:
//   Exact-side wrapper for the proven out_proj scheduler. This preserves the
//   verified datapath while exposing the stage through the refactored exact
//   block boundary.
//---------------------------------------------------------------
module slm_exact_outproj_stage #(
    parameter int TILE_SIZE   = 4,
    parameter int DATA_WIDTH  = 16,
    parameter int ACC_WIDTH   = 32,
    parameter int FRAC_BITS   = 8,
    parameter int N_BANK      = 6,
    parameter int WDEPTH      = 512,
    parameter int WADDR_W     = $clog2(WDEPTH),
    parameter int DATA_W      = 256,
    parameter bit USE_PER_CHANNEL_SCALE = 0,
    parameter string BANK0_INIT_FILE = "",
    parameter string BANK1_INIT_FILE = "",
    parameter string BANK2_INIT_FILE = "",
    parameter string BANK3_INIT_FILE = "",
    parameter string BANK4_INIT_FILE = "",
    parameter string BANK5_INIT_FILE = "",
    parameter string SCALE_INIT_FILE = ""
)(
    input  logic clk,
    input  logic rst_n,
    input  logic enable,
    input  logic start,
    output logic busy,
    output logic done,

    output logic                         p_rd_en,
    output logic [5:0]                   p_rd_addr0,
    output logic [5:0]                   p_rd_addr1,
    output logic [5:0]                   p_rd_addr2,
    output logic [5:0]                   p_rd_addr3,
    input  logic signed [DATA_WIDTH-1:0] p_rd_data0 [TILE_SIZE-1:0],
    input  logic signed [DATA_WIDTH-1:0] p_rd_data1 [TILE_SIZE-1:0],
    input  logic signed [DATA_WIDTH-1:0] p_rd_data2 [TILE_SIZE-1:0],
    input  logic signed [DATA_WIDTH-1:0] p_rd_data3 [TILE_SIZE-1:0],

    output logic                         y_axis_TVALID,
    input  logic                         y_axis_TREADY,
    output logic signed [DATA_WIDTH-1:0] y_axis_TDATA [TILE_SIZE-1:0],

    output logic [1:0]                    fabric_mode,
    output logic [6:0]                    fabric_col_blocks,
    output logic                          fabric_valid_in,
    output logic signed [DATA_WIDTH-1:0]  fabric_A0_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    output logic signed [DATA_WIDTH-1:0]  fabric_A1_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    output logic signed [DATA_WIDTH-1:0]  fabric_A2_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    output logic signed [DATA_WIDTH-1:0]  fabric_A3_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    output logic signed [DATA_WIDTH-1:0]  fabric_B0_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    output logic signed [DATA_WIDTH-1:0]  fabric_B1_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    output logic signed [DATA_WIDTH-1:0]  fabric_B2_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    output logic signed [DATA_WIDTH-1:0]  fabric_B3_mat [TILE_SIZE-1:0][TILE_SIZE-1:0],
    input  logic signed [ACC_WIDTH-1:0]   fabric_reduced_vec [TILE_SIZE-1:0],
    input  logic signed [ACC_WIDTH-1:0]   fabric_reduced_mat_0 [TILE_SIZE-1:0][TILE_SIZE-1:0],
    input  logic signed [ACC_WIDTH-1:0]   fabric_reduced_mat_1 [TILE_SIZE-1:0][TILE_SIZE-1:0],
    input  logic signed [ACC_WIDTH-1:0]   fabric_reduced_mat_2 [TILE_SIZE-1:0][TILE_SIZE-1:0],
    input  logic signed [ACC_WIDTH-1:0]   fabric_reduced_mat_3 [TILE_SIZE-1:0][TILE_SIZE-1:0],
    input  logic                          fabric_valid_out
);
    reuse_out_proj_scheduler #(
        .TILE_SIZE(TILE_SIZE),
        .DATA_WIDTH(DATA_WIDTH),
        .ACC_WIDTH(ACC_WIDTH),
        .FRAC_BITS(FRAC_BITS),
        .N_BANK(N_BANK),
        .WDEPTH(WDEPTH),
        .WADDR_W(WADDR_W),
        .DATA_W(DATA_W),
        .USE_PER_CHANNEL_SCALE(USE_PER_CHANNEL_SCALE),
        .OUTPROJ_BANK0_INIT_FILE(BANK0_INIT_FILE),
        .OUTPROJ_BANK1_INIT_FILE(BANK1_INIT_FILE),
        .OUTPROJ_BANK2_INIT_FILE(BANK2_INIT_FILE),
        .OUTPROJ_BANK3_INIT_FILE(BANK3_INIT_FILE),
        .OUTPROJ_BANK4_INIT_FILE(BANK4_INIT_FILE),
        .OUTPROJ_BANK5_INIT_FILE(BANK5_INIT_FILE),
        .OUTPROJ_SCALE_INIT_FILE(SCALE_INIT_FILE)
    ) u_impl (
        .clk(clk),
        .rst_n(rst_n),
        .enable(enable),
        .start(start),
        .busy(busy),
        .done(done),
        .p_rd_en(p_rd_en),
        .p_rd_addr0(p_rd_addr0),
        .p_rd_addr1(p_rd_addr1),
        .p_rd_addr2(p_rd_addr2),
        .p_rd_addr3(p_rd_addr3),
        .p_rd_data0(p_rd_data0),
        .p_rd_data1(p_rd_data1),
        .p_rd_data2(p_rd_data2),
        .p_rd_data3(p_rd_data3),
        .y_axis_TVALID(y_axis_TVALID),
        .y_axis_TREADY(y_axis_TREADY),
        .y_axis_TDATA(y_axis_TDATA),
        .fabric_mode(fabric_mode),
        .fabric_col_blocks(fabric_col_blocks),
        .fabric_valid_in(fabric_valid_in),
        .fabric_A0_mat(fabric_A0_mat),
        .fabric_A1_mat(fabric_A1_mat),
        .fabric_A2_mat(fabric_A2_mat),
        .fabric_A3_mat(fabric_A3_mat),
        .fabric_B0_mat(fabric_B0_mat),
        .fabric_B1_mat(fabric_B1_mat),
        .fabric_B2_mat(fabric_B2_mat),
        .fabric_B3_mat(fabric_B3_mat),
        .fabric_reduced_vec(fabric_reduced_vec),
        .fabric_reduced_mat_0(fabric_reduced_mat_0),
        .fabric_reduced_mat_1(fabric_reduced_mat_1),
        .fabric_reduced_mat_2(fabric_reduced_mat_2),
        .fabric_reduced_mat_3(fabric_reduced_mat_3),
        .fabric_valid_out(fabric_valid_out)
    );
endmodule

