@echo off
REM ****************************************************************************
REM Vivado (TM) v2024.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Tue Apr 14 02:00:44 +0200 2026
REM SW Build 5076996 on Wed May 22 18:37:14 MDT 2024
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim tb_reuse_mamba_board_shell_ps_behav -key {Behavioral:sim_3:Functional:tb_reuse_mamba_board_shell_ps} -tclbatch tb_reuse_mamba_board_shell_ps.tcl -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/bd_886d.protoinst" -view E:/course/smamba/HW_reconstruct/project_mamba_all1/tb_reuse_in_proj_scheduler_behav.wcfg -log simulate.log"
call xsim  tb_reuse_mamba_board_shell_ps_behav -key {Behavioral:sim_3:Functional:tb_reuse_mamba_board_shell_ps} -tclbatch tb_reuse_mamba_board_shell_ps.tcl -protoinst "protoinst_files/bd_48ac.protoinst" -protoinst "protoinst_files/bd_886d.protoinst" -view E:/course/smamba/HW_reconstruct/project_mamba_all1/tb_reuse_in_proj_scheduler_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
