read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/axis_vec_join2.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/bias_add_regslice_ip.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/ew_update_vec4.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/ewa_vec4.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/ewm_gate_sbuf_vec4.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/ewm_vec4.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/pe_unit_pipe.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/pulse_to_stream_adapter.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/requant_round_sat_engine.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_array4x4.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_block_ctrl.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_block_pipeline_ctrl.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_ht_multi_copy_ip.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_ht_sram.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_ht_sram_sp.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_in_proj_scheduler.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_inproj_weight_sram.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mac_fabric_manager.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_4block_chain_top.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_axi_lite_regs.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_block_top.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_block_wrapper.sv"
read_verilog "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_board_shell_stream.v"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_chain4_core_adapter.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_core_adapter.sv"
read_verilog "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_mamba_h_stream_loader.v"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_norm_raw_h_sram.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_norm_weight_mem.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_out_proj_scheduler.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_outproj_weight_sram.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_packed_scale_mem.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_pipeline_4array_top.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_pipeline_4array_with_reduction.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_pt_capture.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_reduction_accumulator.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_rmsnorm_scheduler.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_runtime_scale_lane_seq.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_shared_mac_fabric.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_silu_vec4.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_slim_mac_mem_controller_combined_dp.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_ssm_core.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_ssm_dt_scheduler.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_ssm_state_reset_ctrl.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_state_scale_pingpong.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_top_mac_plus_bias_fifo_sigmoid_ew_gate.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_u32_div_seq.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_vec_out_sram.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_vec_out_sram_ip.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_weight_bank_rom.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/reuse_z_stream_reader.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/sigmoid4_vec.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/slim_multi_bank_wbuf_dp.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/vec_fifo_axis_ip.sv"
read_verilog -sv "E:/course/smamba/final_hw/rtl_reuse_shared/xt_input_buf.sv"
read_verilog "E:/course/smamba/final_hw/project_mamba_final_hw/project_mamba_final_hw.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo_stub.v"
read_verilog "E:/course/smamba/final_hw/project_mamba_final_hw/project_mamba_final_hw.gen/sources_1/ip/bias_ROM/bias_ROM_stub.v"
read_verilog "E:/course/smamba/final_hw/project_mamba_final_hw/project_mamba_final_hw.gen/sources_1/ip/inproj_ht_sram_ip/inproj_ht_sram_ip_stub.v"
read_verilog "E:/course/smamba/final_hw/project_mamba_final_hw/project_mamba_final_hw.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_stub.v"
read_verilog "E:/course/smamba/final_hw/project_mamba_final_hw/project_mamba_final_hw.gen/sources_1/ip/s_buffer/s_buffer_stub.v"
synth_design -top reuse_state_scale_pingpong -part xczu9eg-ffvb1156-2-e -flatten_hierarchy rebuilt
if {[llength [get_ports clk]] > 0} { create_clock -period 6.0 -name clk [get_ports clk] }
if {[llength [get_ports sys_clk]] > 0} { create_clock -period 6.0 -name sys_clk [get_ports sys_clk] }
report_timing_summary -delay_type max -max_paths 10 -file "E:/course/smamba/final_hw/synth_runs/reuse_state_scale_pingpong_p6p0/timing_summary.rpt"
report_utilization -file "E:/course/smamba/final_hw/synth_runs/reuse_state_scale_pingpong_p6p0/utilization.rpt"
write_checkpoint -force "E:/course/smamba/final_hw/synth_runs/reuse_state_scale_pingpong_p6p0/post_synth.dcp"
quit
