set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:1 order:EARLY scoped_inst:{u_dt_sched/u_wbuf/WBUF_BANK[0].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:2 order:EARLY scoped_inst:{u_dt_sched/u_wbuf/WBUF_BANK[1].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:3 order:EARLY scoped_inst:{u_dt_sched/u_wbuf/WBUF_BANK[2].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:4 order:EARLY scoped_inst:{u_dt_sched/u_wbuf/WBUF_BANK[3].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:5 order:EARLY scoped_inst:{u_dt_sched/u_wbuf/WBUF_BANK[4].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:6 order:EARLY scoped_inst:{u_dt_sched/u_wbuf/WBUF_BANK[5].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:7 order:EARLY scoped_inst:{u_in_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:8 order:EARLY scoped_inst:{u_in_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:9 order:EARLY scoped_inst:{u_in_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:10 order:EARLY scoped_inst:{u_in_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:11 order:EARLY scoped_inst:{u_in_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/slim_WBUF_bank_dp/slim_WBUF_bank_dp/slim_WBUF_bank_dp_in_context.xdc id:12 order:EARLY scoped_inst:{u_in_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias_ROM/bias_ROM/bias_ROM_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/bias_ROM/bias_ROM/bias_ROM_in_context.xdc id:13 order:EARLY scoped_inst:u_ssm_core/u_bias_add/u_bias_rom} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/s_buffer/s_buffer/s_buffer_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/s_buffer/s_buffer/s_buffer_in_context.xdc id:14 order:EARLY scoped_inst:u_ssm_core/u_ew/u_s_buffer} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc id:15 order:EARLY scoped_inst:u_dt_sched/u_xt_vec_fifo/u_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc id:16 order:EARLY scoped_inst:u_u_silu/u_x_fifo/u_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc id:17 order:EARLY scoped_inst:u_silu/u_x_fifo/u_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc id:18 order:EARLY scoped_inst:u_ssm_core/u_bias_fifo/u_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/bias2sigmoid_fifo/bias2sigmoid_fifo/bias2sigmoid_fifo_in_context.xdc id:19 order:EARLY scoped_inst:u_ssm_core/u_lam_fifo/u_fifo} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:20 order:EARLY scoped_inst:u_in_proj/u_h_sram/u_ht_ip/u_copy0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:21 order:EARLY scoped_inst:u_in_proj/u_h_sram/u_ht_ip/u_copy1} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:22 order:EARLY scoped_inst:u_in_proj/u_h_sram/u_ht_ip/u_copy2} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:23 order:EARLY scoped_inst:u_in_proj/u_h_sram/u_ht_ip/u_copy3} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:24 order:EARLY scoped_inst:u_uact_sram/u_ht_ip} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:25 order:EARLY scoped_inst:u_p_sram/u_ht_ip/u_copy0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:26 order:EARLY scoped_inst:u_p_sram/u_ht_ip/u_copy1} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:27 order:EARLY scoped_inst:u_p_sram/u_ht_ip/u_copy2} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip_1/inproj_ht_sram_ip/inproj_ht_sram_ip_in_context.xdc id:28 order:EARLY scoped_inst:u_p_sram/u_ht_ip/u_copy3} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc id:29 order:EARLY scoped_inst:{u_out_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc id:30 order:EARLY scoped_inst:{u_out_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc id:31 order:EARLY scoped_inst:{u_out_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc id:32 order:EARLY scoped_inst:{u_out_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc id:33 order:EARLY scoped_inst:{u_out_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp/outproj_WBUF_bank_dp_in_context.xdc id:34 order:EARLY scoped_inst:{u_out_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank}} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc id:35 order:EARLY scoped_inst:u_in_proj/u_u_sram/u_vec_ip/u_copy0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc id:36 order:EARLY scoped_inst:u_in_proj/u_u_sram/u_vec_ip/u_copy1} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc id:37 order:EARLY scoped_inst:u_in_proj/u_z_sram/u_vec_ip/u_copy0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc id:38 order:EARLY scoped_inst:u_in_proj/u_z_sram/u_vec_ip/u_copy1} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc id:39 order:EARLY scoped_inst:u_out_proj/u_y_sram/u_vec_ip/u_copy0} [current_design]
set_property SRC_FILE_INFO {cfile:e:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc rfile:../../../../../project_mamba_all1.gen/sources_1/ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip/inproj_vec_out_sram_ip_in_context.xdc id:40 order:EARLY scoped_inst:u_out_proj/u_y_sram/u_vec_ip/u_copy1} [current_design]
set_property SRC_FILE_INFO {cfile:E:/course/master/mamba/Cmamba_reconstruct/HW_reconstruct/minimal_timing.xdc rfile:../../../../../../minimal_timing.xdc id:41} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[0].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[0].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[0].u_bank}]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[1].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[1].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:2 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[1].u_bank}]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[2].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[2].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:3 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[2].u_bank}]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[3].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[3].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:4 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[3].u_bank}]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[4].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[4].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:5 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[4].u_bank}]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[5].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_dt_sched/u_wbuf/WBUF_BANK[5].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:6 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[5].u_bank}]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:7 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank}]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:8 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank}]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:9 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank}]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:10 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank}]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:11 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank}]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_in_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:12 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank}]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_ssm_core/u_bias_add/u_bias_rom/clka]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ssm_core/u_bias_add/u_bias_rom]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_ssm_core/u_ew/u_s_buffer/clka]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_ssm_core/u_ew/u_s_buffer/clkb]
set_property src_info {type:SCOPED_XDC file:14 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ssm_core/u_ew/u_s_buffer]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_dt_sched/u_xt_vec_fifo/u_fifo/s_aclk]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_dt_sched/u_xt_vec_fifo/u_fifo]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_u_silu/u_x_fifo/u_fifo/s_aclk]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_u_silu/u_x_fifo/u_fifo]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_silu/u_x_fifo/u_fifo/s_aclk]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_silu/u_x_fifo/u_fifo]
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_ssm_core/u_bias_fifo/u_fifo/s_aclk]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ssm_core/u_bias_fifo/u_fifo]
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins u_ssm_core/u_lam_fifo/u_fifo/s_aclk]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_ssm_core/u_lam_fifo/u_fifo]
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy0/clka]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy0/clkb]
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy0]
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy1/clka]
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy1/clkb]
set_property src_info {type:SCOPED_XDC file:21 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy1]
set_property src_info {type:SCOPED_XDC file:22 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy2/clka]
set_property src_info {type:SCOPED_XDC file:22 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy2/clkb]
set_property src_info {type:SCOPED_XDC file:22 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy2]
set_property src_info {type:SCOPED_XDC file:23 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy3/clka]
set_property src_info {type:SCOPED_XDC file:23 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_h_sram/u_ht_ip/u_copy3/clkb]
set_property src_info {type:SCOPED_XDC file:23 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy3]
set_property src_info {type:SCOPED_XDC file:24 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_uact_sram/u_ht_ip/clka]
set_property src_info {type:SCOPED_XDC file:24 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_uact_sram/u_ht_ip/clkb]
set_property src_info {type:SCOPED_XDC file:24 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_uact_sram/u_ht_ip]
set_property src_info {type:SCOPED_XDC file:25 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy0/clka]
set_property src_info {type:SCOPED_XDC file:25 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy0/clkb]
set_property src_info {type:SCOPED_XDC file:25 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_p_sram/u_ht_ip/u_copy0]
set_property src_info {type:SCOPED_XDC file:26 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy1/clka]
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy1/clkb]
set_property src_info {type:SCOPED_XDC file:26 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_p_sram/u_ht_ip/u_copy1]
set_property src_info {type:SCOPED_XDC file:27 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy2/clka]
set_property src_info {type:SCOPED_XDC file:27 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy2/clkb]
set_property src_info {type:SCOPED_XDC file:27 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_p_sram/u_ht_ip/u_copy2]
set_property src_info {type:SCOPED_XDC file:28 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy3/clka]
set_property src_info {type:SCOPED_XDC file:28 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_p_sram/u_ht_ip/u_copy3/clkb]
set_property src_info {type:SCOPED_XDC file:28 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_p_sram/u_ht_ip/u_copy3]
set_property src_info {type:SCOPED_XDC file:29 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:29 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:29 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank}]
set_property src_info {type:SCOPED_XDC file:30 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:30 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:30 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank}]
set_property src_info {type:SCOPED_XDC file:31 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:31 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:31 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank}]
set_property src_info {type:SCOPED_XDC file:32 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:32 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:32 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank}]
set_property src_info {type:SCOPED_XDC file:33 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:33 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:33 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank}]
set_property src_info {type:SCOPED_XDC file:34 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank/clka}]
set_property src_info {type:SCOPED_XDC file:34 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {u_out_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank/clkb}]
set_property src_info {type:SCOPED_XDC file:34 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank}]
set_property src_info {type:SCOPED_XDC file:35 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_u_sram/u_vec_ip/u_copy0/clka]
set_property src_info {type:SCOPED_XDC file:35 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_u_sram/u_vec_ip/u_copy0/clkb]
set_property src_info {type:SCOPED_XDC file:35 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_u_sram/u_vec_ip/u_copy0]
set_property src_info {type:SCOPED_XDC file:36 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_u_sram/u_vec_ip/u_copy1/clka]
set_property src_info {type:SCOPED_XDC file:36 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_u_sram/u_vec_ip/u_copy1/clkb]
set_property src_info {type:SCOPED_XDC file:36 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_u_sram/u_vec_ip/u_copy1]
set_property src_info {type:SCOPED_XDC file:37 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_z_sram/u_vec_ip/u_copy0/clka]
set_property src_info {type:SCOPED_XDC file:37 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_z_sram/u_vec_ip/u_copy0/clkb]
set_property src_info {type:SCOPED_XDC file:37 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_z_sram/u_vec_ip/u_copy0]
set_property src_info {type:SCOPED_XDC file:38 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_z_sram/u_vec_ip/u_copy1/clka]
set_property src_info {type:SCOPED_XDC file:38 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_in_proj/u_z_sram/u_vec_ip/u_copy1/clkb]
set_property src_info {type:SCOPED_XDC file:38 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_in_proj/u_z_sram/u_vec_ip/u_copy1]
set_property src_info {type:SCOPED_XDC file:39 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_out_proj/u_y_sram/u_vec_ip/u_copy0/clka]
set_property src_info {type:SCOPED_XDC file:39 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_out_proj/u_y_sram/u_vec_ip/u_copy0/clkb]
set_property src_info {type:SCOPED_XDC file:39 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_out_proj/u_y_sram/u_vec_ip/u_copy0]
set_property src_info {type:SCOPED_XDC file:40 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_out_proj/u_y_sram/u_vec_ip/u_copy1/clka]
set_property src_info {type:SCOPED_XDC file:40 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins u_out_proj/u_y_sram/u_vec_ip/u_copy1/clkb]
set_property src_info {type:SCOPED_XDC file:40 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_out_proj/u_y_sram/u_vec_ip/u_copy1]
set_property src_info {type:XDC file:41 line:10 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 2.500 -name sys_clk [get_ports clk]
set_property src_info {type:XDC file:41 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_false_path -from [get_ports rst_n]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[0].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[1].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[2].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[3].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[4].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_dt_sched/u_wbuf/WBUF_BANK[5].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_in_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ssm_core/u_bias_add/u_bias_rom]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ssm_core/u_ew/u_s_buffer]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_dt_sched/u_xt_vec_fifo/u_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_u_silu/u_x_fifo/u_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_silu/u_x_fifo/u_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ssm_core/u_bias_fifo/u_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_ssm_core/u_lam_fifo/u_fifo]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_p_sram/u_ht_ip/u_copy0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_p_sram/u_ht_ip/u_copy1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_p_sram/u_ht_ip/u_copy2]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_h_sram/u_ht_ip/u_copy3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_p_sram/u_ht_ip/u_copy3]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_uact_sram/u_ht_ip]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[0].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[1].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[2].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[3].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[4].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {u_out_proj/u_w_sram/u_weight/WBUF_BANK[5].u_bank}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_u_sram/u_vec_ip/u_copy0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_z_sram/u_vec_ip/u_copy0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_out_proj/u_y_sram/u_vec_ip/u_copy0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_u_sram/u_vec_ip/u_copy1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_in_proj/u_z_sram/u_vec_ip/u_copy1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_out_proj/u_y_sram/u_vec_ip/u_copy1]
