# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/inproj_ht_sram_ip/inproj_ht_sram_ip.xci
# IP: The module: 'inproj_ht_sram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip/inproj_ht_sram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inproj_ht_sram_ip'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.srcs/sources_1/ip/inproj_ht_sram_ip/inproj_ht_sram_ip.xci
# IP: The module: 'inproj_ht_sram_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/course/smamba/HW_reconstruct/project_mamba_all1/project_mamba_all1.gen/sources_1/ip/inproj_ht_sram_ip/inproj_ht_sram_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'inproj_ht_sram_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
